apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jira-adapter-v1
  labels:
    app: jira-adapter-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jira-adapter-v1
  template:
    metadata:
      labels:
        app: jira-adapter-v1
    spec:
      containers:
      - name: jira-adapter-v1
        image: consortit-docker-cme-local.jfrog.io/jira-adapter:image-version
        ports:
        - containerPort: 8080
        - containerPort: 8081        
        env:        
        - name: jiraUserPassword
          valueFrom:
            secretKeyRef:
              name: jira-adapter-secret
              key: jiraUserPassword        
        - name: jwk_kid
          valueFrom:
            secretKeyRef:
              name: jira-adapter-secret
              key: jwk_kid        
      imagePullSecrets:
        - name: regsecret        
---
apiVersion: v1
kind: Service
metadata:
  name: jira-adapter-v1
  labels:
   app: jira-adapter-v1
   version: v1   
spec:  
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: external
    - port: 81
      protocol: TCP
      targetPort: 8081
      name: health
  selector:
    app: jira-adapter-v1 
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jira-adapter-v1
  labels:
    application: jira-adapter-v1
spec:
  rules:
   - host: "cme.dev.k8s.consort-it.de"
     http:
      paths:
      - path: /api/v1/jira-adapter/issues
        backend:
          serviceName: jira-adapter-v1
          servicePort: 80
      - path: /api/v1/jira-adapter/health
        backend:
          serviceName: jira-adapter-v1
          servicePort: 81
      - path: /api/v1/jira-adapter/metrics
        backend:
          serviceName: jira-adapter-v1
          servicePort: 81